# Generated by Django 4.0.4 on 2024-12-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
