# Generated by Django 4.0.4 on 2024-12-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0006_dichvu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dichvu',
            name='gia',
            field=models.IntegerField(),
        ),
    ]
